export const ROUTES = {
	HOME: '/',
	CONTRIBUTING: '/contributing',
	CHANGELOG: 'https://github.com/htmlplus/ui/blob/main/CHANGELOG.md',
	VISION: '/vision',
	CODE_COMPLETION: '/code-completion',
	ANIMATIONS: '/element/animation/names',
	ICONS: 'https://icons.getbootstrap.com',
	BIDIRECTIONALITY: '/bidirectionality',
	SETUP: '/setup',
	BREAKPOINTS: '/breakpoints',
	GLOBAL_CONFIGURATION: '/global-configuration',
	OVERRIDES_PROPERTY: '/overrides-property',
	VARIANT_PROPERTY: '/variant-property',
	COLOR_PROPERTIES: '/color-properties',
	DISABLE_APIS: '/disable-apis',
	OVERVIEW: '/overview',
	ROADMAP: '/roadmap',
	INSTALLATION: '/installation',
	INSTALLATION_FRAMEWORK: '/[framework]/installation',
	BROWSERS: '/browsers',
	ELEMENT_DETAILS: '/[framework]/element/[element]',
	ELEMENT_EXAMPLE: '/element/[element]/example/[example]',
	ELEMENT_CONFIG: '/element/[element]/config',
	API_DETAILS: '/[framework]/api/[element]',
	CODEOFCONDUCT: '/code-of-conduct',
	GITHUB_URL: 'https://github.com/htmlplus/ui',
	ASSETS: '/assets/[filepath]',
	CONTRIBUTOR: 'https://github.com/[contributor].png?size=[size:number]',
	CONTRIBUTOR_GITHUB: 'https://github.com/[contributor]',
	SOCIAL_TWITTER: 'https://www.twitter.com/htmlplusio',
	SOCIAL_LINKEDIN: 'https://www.linkedin.com/company/htmlplus',
	SOCIAL_INSTAGRAM: 'https://www.instagram.com/htmlplus.io',
	SOCIAL_GITHUB: 'https://github.com/htmlplus/htmlplus',
	SOCIAL_YOUTUBE: 'https://www.youtube.com/channel/UCsNkxDmLU7vK_L1jgSVWWCA',
	GITHUB_COMMITS: 'https://api.github.com/repos/htmlplus/[repository]/commits?path=[path]',
	EXAMPLE_STACKBLITZ_LINK:
		'https://stackblitz.com/github/htmlplus/examples/tree/main/dist/[framework]/[element]/[example]',
	EXAMPLE_GITHUB_LINK:
		'https://github.com/htmlplus/examples/tree/main/dist/[framework]/[element]/[example]',
	EXAMPLE_DOWNLOAD_LINK:
		'https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/htmlplus/examples/tree/main/dist/[framework]/[element]/[example]',
	TYPE_GITHUB_LINK: 'https://github.com/htmlplus/ui/tree/main/src/elements/[element]/[fileName]'
} as const;
