declare module '@htmlplus/ui' {
	interface PlusConfigOverrides {
		color:
			| 'alpha-black-1'
			| 'alpha-black-2'
			| 'alpha-black-3'
			| 'alpha-black-4'
			| 'alpha-black-6'
			| 'alpha-black-7'
			| 'alpha-black-8'
			| 'alpha-black-9'
			| 'alpha-black-10'
			| 'alpha-black-11'
			| 'alpha-black-12'
			| 'main-1'
			| 'main-2'
			| 'main-3'
			| 'main-4'
			| 'main-5'
			| 'main-6'
			| 'main-7'
			| 'main-8'
			| 'main-9'
			| 'main-10'
			| 'main-11'
			| 'main-12'
			| 'primary-1'
			| 'primary-2'
			| 'primary-3'
			| 'primary-4'
			| 'primary-5'
			| 'primary-6'
			| 'primary-7'
			| 'primary-8'
			| 'primary-9'
			| 'primary-10'
			| 'primary-11'
			| 'primary-12';
	}
	interface PlusIconOverrides {
		name:
			| 'arrow-clockwise'
			| 'arrow-right-short'
			| 'arrow-right'
			| 'bell'
			| 'brush'
			| 'caret-right-fill'
			| 'chevron-compact-right'
			| 'chevron-left'
			| 'chevron-right'
			| 'circle-fill'
			| 'clipboard'
			| 'dash'
			| 'download'
			| 'gear'
			| 'github'
			| 'heart'
			| 'house'
			| 'htmlplus'
			| 'list'
			| 'person'
			| 'plus'
			| 'puzzle'
			| 'sign-turn-left'
			| 'stackblitz'
			| 'tag'
			| 'telephone';
	}
}

export {};
